EXPERIMENT:
  name: brats2020_3d_text_adapter
  seed: 42
  output_dir: ./brats3d_outputs/full

DATA:
  dataset_root: D:/Users/admin/Data/BraTS 2020 text
  h5_data_dir: D:/Users/admin/Data/BraTS 2020 text/BraTS2020_training_data/content/data
  text_dir: D:/Users/admin/Data/BraTS 2020 text/TextBraTSData
  metadata_csv: D:/Users/admin/Data/BraTS 2020 text/BraTS2020_training_data/content/data/meta_data.csv
  split_dir: ./brats3d_outputs/splits_seed42
  split_seed: 42
  train_ratio: 0.7
  val_ratio: 0.1
  test_ratio: 0.2
  image_key: image
  mask_key: mask
  channel_names: [channel_0, channel_1, channel_2, channel_3]
  label_names: [background, ncr_net, edema, enhancing]
  wavelet_type: haar
  patch_size: [64, 128, 128]
  foreground_patch_prob: 0.8
  normalize_nonzero: true
  train_cases_limit:
  val_cases_limit:
  test_cases_limit:

TEXT:
  bert_type: ./lib/BiomedVLP-CXR-BERT-specialized
  max_text_length: 192
  freeze_text_encoder: true
  adapter_enabled: true
  adapter_bottleneck_dim: 192
  adapter_dropout: 0.1

MODEL:
  in_channels: 4
  num_classes: 4
  base_channels: 16
  text_dim: 768
  fusion_dim: 64
  num_heads: 4

TRAIN:
  device: auto
  epochs: 200
  max_train_steps: 0
  max_val_steps: 0
  batch_size: 1
  num_workers: 2
  lr_image: 0.0002
  lr_text_adapter: 0.0002
  lr_text_encoder: 0.00001
  weight_decay: 0.00001
  ce_weight: 1.0
  dice_weight: 1.0
  amp: true
  grad_clip: 1.0
  patience: 30
  save_best_metric: mean_dice

INFER:
  roi_size: [64, 128, 128]
  sw_batch_size: 1
  overlap: 0.25

TEST:
  run_test_after_train: true
  save_predictions: false
