TRAIN:
  train_batch_size: 12
  lr: 0.00012
  valid_batch_size: 6
  image_size: [224,224]
  min_epochs: 20
  max_epochs: 200
  patience: 30
  device: 1
  model_save_path: ./save_model
  model_save_filename: qataseg

MODEL:
  bert_type: ./lib/BiomedVLP-CXR-BERT-specialized
  vision_type: ./lib/convnext-tiny-224
  project_dim: 768

# QaTa-COV19
#DATA:
#  train_csv_path:
#  train_root_path:
#
#  valid_csv_path:
#  valid_root_path:
#
#  test_csv_path:
#  test_root_path:

#MosMedData+
DATA:
   train_csv_path:
   train_root_path:

   valid_csv_path:
   valid_root_path:

   test_csv_path:
   test_root_path:
